// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BdFileBlock.proto

#ifndef PROTOBUF_BdFileBlock_2eproto__INCLUDED
#define PROTOBUF_BdFileBlock_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_BdFileBlock_2eproto();
void protobuf_InitDefaults_BdFileBlock_2eproto();
void protobuf_AssignDesc_BdFileBlock_2eproto();
void protobuf_ShutdownFile_BdFileBlock_2eproto();

class BdFileBlock;

// ===================================================================

class BdFileBlock : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BdFileBlock) */ {
 public:
  BdFileBlock();
  virtual ~BdFileBlock();

  BdFileBlock(const BdFileBlock& from);

  inline BdFileBlock& operator=(const BdFileBlock& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BdFileBlock& default_instance();

  static const BdFileBlock* internal_default_instance();

  void Swap(BdFileBlock* other);

  // implements Message ----------------------------------------------

  inline BdFileBlock* New() const { return New(NULL); }

  BdFileBlock* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BdFileBlock& from);
  void MergeFrom(const BdFileBlock& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BdFileBlock* other);
  void UnsafeMergeFrom(const BdFileBlock& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 offset = 1;
  bool has_offset() const;
  void clear_offset();
  static const int kOffsetFieldNumber = 1;
  ::google::protobuf::uint64 offset() const;
  void set_offset(::google::protobuf::uint64 value);

  // required bytes data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:BdFileBlock)
 private:
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_data();
  inline void clear_has_data();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::uint64 offset_;
  friend void  protobuf_InitDefaults_BdFileBlock_2eproto_impl();
  friend void  protobuf_AddDesc_BdFileBlock_2eproto_impl();
  friend void protobuf_AssignDesc_BdFileBlock_2eproto();
  friend void protobuf_ShutdownFile_BdFileBlock_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<BdFileBlock> BdFileBlock_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BdFileBlock

// required uint64 offset = 1;
inline bool BdFileBlock::has_offset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BdFileBlock::set_has_offset() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BdFileBlock::clear_has_offset() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BdFileBlock::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::uint64 BdFileBlock::offset() const {
  // @@protoc_insertion_point(field_get:BdFileBlock.offset)
  return offset_;
}
inline void BdFileBlock::set_offset(::google::protobuf::uint64 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:BdFileBlock.offset)
}

// required bytes data = 2;
inline bool BdFileBlock::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BdFileBlock::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BdFileBlock::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BdFileBlock::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& BdFileBlock::data() const {
  // @@protoc_insertion_point(field_get:BdFileBlock.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BdFileBlock::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BdFileBlock.data)
}
inline void BdFileBlock::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BdFileBlock.data)
}
inline void BdFileBlock::set_data(const void* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BdFileBlock.data)
}
inline ::std::string* BdFileBlock::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:BdFileBlock.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BdFileBlock::release_data() {
  // @@protoc_insertion_point(field_release:BdFileBlock.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BdFileBlock::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:BdFileBlock.data)
}

inline const BdFileBlock* BdFileBlock::internal_default_instance() {
  return &BdFileBlock_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BdFileBlock_2eproto__INCLUDED
