// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BdBlock.proto

#ifndef PROTOBUF_BdBlock_2eproto__INCLUDED
#define PROTOBUF_BdBlock_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_BdBlock_2eproto();
void protobuf_InitDefaults_BdBlock_2eproto();
void protobuf_AssignDesc_BdBlock_2eproto();
void protobuf_ShutdownFile_BdBlock_2eproto();

class BdBlock;

// ===================================================================

class BdBlock : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BdBlock) */ {
 public:
  BdBlock();
  virtual ~BdBlock();

  BdBlock(const BdBlock& from);

  inline BdBlock& operator=(const BdBlock& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BdBlock& default_instance();

  static const BdBlock* internal_default_instance();

  void Swap(BdBlock* other);

  // implements Message ----------------------------------------------

  inline BdBlock* New() const { return New(NULL); }

  BdBlock* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BdBlock& from);
  void MergeFrom(const BdBlock& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BdBlock* other);
  void UnsafeMergeFrom(const BdBlock& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 offset = 1;
  bool has_offset() const;
  void clear_offset();
  static const int kOffsetFieldNumber = 1;
  ::google::protobuf::uint32 offset() const;
  void set_offset(::google::protobuf::uint32 value);

  // required string message = 2;
  bool has_message() const;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:BdBlock)
 private:
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_message();
  inline void clear_has_message();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::uint32 offset_;
  friend void  protobuf_InitDefaults_BdBlock_2eproto_impl();
  friend void  protobuf_AddDesc_BdBlock_2eproto_impl();
  friend void protobuf_AssignDesc_BdBlock_2eproto();
  friend void protobuf_ShutdownFile_BdBlock_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<BdBlock> BdBlock_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BdBlock

// required uint32 offset = 1;
inline bool BdBlock::has_offset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BdBlock::set_has_offset() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BdBlock::clear_has_offset() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BdBlock::clear_offset() {
  offset_ = 0u;
  clear_has_offset();
}
inline ::google::protobuf::uint32 BdBlock::offset() const {
  // @@protoc_insertion_point(field_get:BdBlock.offset)
  return offset_;
}
inline void BdBlock::set_offset(::google::protobuf::uint32 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:BdBlock.offset)
}

// required string message = 2;
inline bool BdBlock::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BdBlock::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BdBlock::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BdBlock::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message();
}
inline const ::std::string& BdBlock::message() const {
  // @@protoc_insertion_point(field_get:BdBlock.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BdBlock::set_message(const ::std::string& value) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BdBlock.message)
}
inline void BdBlock::set_message(const char* value) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BdBlock.message)
}
inline void BdBlock::set_message(const char* value, size_t size) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BdBlock.message)
}
inline ::std::string* BdBlock::mutable_message() {
  set_has_message();
  // @@protoc_insertion_point(field_mutable:BdBlock.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BdBlock::release_message() {
  // @@protoc_insertion_point(field_release:BdBlock.message)
  clear_has_message();
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BdBlock::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    set_has_message();
  } else {
    clear_has_message();
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:BdBlock.message)
}

inline const BdBlock* BdBlock::internal_default_instance() {
  return &BdBlock_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BdBlock_2eproto__INCLUDED
